# Generated by Django 5.2.1 on 2025-05-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_part_category_part_created_at_alter_part_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
            ],
            options={
                'permissions': [('view_inventory', 'Can view inventory'), ('manage_inventory', 'Can add or delete inventory')],
            },
        ),
    ]
