# Generated by Django 5.2.1 on 2025-06-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_inventoryitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='description',
        ),
        migrations.AlterField(
            model_name='part',
            name='category',
            field=models.CharField(choices=[('Engine', 'Engine'), ('Brakes', 'Brakes'), ('Suspension', 'Suspension'), ('Electrical', 'Electrical'), ('Interior', 'Interior'), ('Body', 'Body'), ('Tires', 'Tires')], max_length=50),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
