# Generated by Django 5.2.1 on 2025-06-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_part_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='description',
        ),
    ]
